In [3]:
# Задание 1
import numpy as np

n = 10
diag_1 = np.arange(n-1, -1, -1)

diag_1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
# Задание 2
my_array = np.diag(diag_1)
my_sum = sum(diag_1)

print(my_array)
print("diagonal sum: ", my_sum)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
diagonal sum:  45


In [6]:
# Задание 3

# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
result = np.linalg.solve(a, b)
print("x, y, z =", result)




x, y, z = [ 0.46666667  3.84444444 -5.55555556]


In [7]:
# Задание 4
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

angls = {}
for id, user in enumerate(users_stats):
    angls[id+1] = np.arccos(cosine(user, next_user_stats)) * 360 / 2 / np.pi
id_min = min(angls, key=lambda unit: angls[unit])

print(f'id пользователя: {id_min}, между которым минимальный угол: {angls[id_min]} градусов')

id пользователя: 8, между которым минимальный угол: 18.434948822922017 градусов
